name: Page Consulting
markdown: kramdown
highlighter: rouge
exclude: [serve.sh, README.md, .gitignore, 'components',
  'node_modules',
  'GruntFile.js',
  'package.json']
navigation: [ services, whoweare, clients, jot ]
