name: Page Consulting
markdown: redcarpet
pygments: true
baseurl: "http://tonyscottpage.github.io/site"
exclude: [serve.sh, README.md, .gitignore]
navigation: [ services, journal, clients, whoweare, contact ]